### ISSUE TITLE
feat: 최초 로그인 기능 생성

### ISSUE THREAD

**Issue by sootudio** [strangebros/nork-backend#1]
### 작업 개요
- 로그인 API 작성, JWT token 생성 파트 제외

### 작업 내용
- 토큰을 생성하는 최초 로그인 API 생성

### Todo list
- [ ] application.properties에 db 정보 저장
- [ ] member entity 코드 작성 service와 db를 연결할 때 사용
- [ ] member.controller, member.service에서 비즈니스 로직 코드 작성
    - [ ] controller에서 service로 요청 보낼 때, 로그인 requestDto 작성하여 사용
    - [ ] service에서 controller로 응답 보낼 때, 로그인 responseDto 작성하여 사용
- [ ] member.mapper 생성 후 매핑 코드 작성
