### ISSUE TITLE
feat: 회원가입 API 개발

### ISSUE THREAD

**Issue by sootudio** [strangebros/nork-backend#15]
### 작업 개요
- 회원가입 기능 개발

### 작업 내용
- 회원가입에 필요한 메소드 및 테스트 작성
- 회원가입 시 jwt 토큰 생성해서 바로 로그인 시켜주도록 만든다.

### Todo list
- [x] SignUp 관련 dto 만들기
- [x] MemberController에 signUp 메소드 추가
- [x] MemberService에 signUp 메소드 추가
- [x] MemberMapper에 데이터 넣는 함수 추가
- [x] mapper/member.xml에 sql 추가
- [x] 테스트 메소드 생성 후 기능 테스트
