### ISSUE TITLE
fix: database table의 id auto increment 설정 / 추가 컬럼들 수정

### ISSUE THREAD

**Issue by sootudio** [strangebros/nork-backend#16]
### 예외 개요
- db의 모든 table의 id 컬럼에 ai 속성이 설정되어있지 않음
- 원래는 다 되어 있어야 함.
- 그 외에 API 설계 과정에서 기존 테이블 설정에 문제들 수정할 필요성을 느낌

### 예외 원인
- member table의 id가 ai 설정이 되어있지 않아서, 회원가입 API가 작동하지 않음
- member 프로필을 base64로 저장하게 되면서, profile_image 컬럼이 필요해짐.
- visited_space에 최신 방문 일자를 직접 저장할 필요성도 느낌 - 원래는 visited_review에 가서 가져왔는데, 장소 리스트를 보여주는 화면에서 계속 visited_review에 접근해서 최신 일자를 가져오는 로직이 비효율적이라고 생각했음.
- visited_review에서 visited_space id를 가져오는 것 보다, member id와 workspace_id를 직접 fk로 가져오는 것이 더 적절하다고 생각했음.

### 작업 내용
- db 테이블들에서 id 컬럼들 속성으로 ai 넣어주기 (dataGrip에서 작업)
- spinrg project에 있는 sql 파일 수정

### Todo list
id 컬럼 ai 설정
- [x]  foreign keys가 설정된 테이블들 해제( reservation, review_keyword, visited_review, visited_review_image, visited_space, worksapce_keyword)
- [x]  member table id ai 설정
- [x]  workspace table id ai 설정
- [x]  keyword table id ai 설정
- [x]  reservation table 생성 &  id ai 설정
- [x]  visited_space table 생성 &  id ai 설정
- [x]  visited_review table 생성 &  id ai 설정
- [x]  visited_review_image table 생성 &  id ai 설정
- [x]  workspace_keyword table 생성 &  id ai 설정
- [x]  review_keyword table 생성 &  id ai 설정

그 외 컬럼 수정 & sql 작업
- [x] member table에 profile_image 추가
- [x]  visited_review 에서 visited_space_id 컬럼 삭제, member_id, workspace_id를 추가하고 fk로 등록
- [x]  visited_space table에 recent_visited_datetime 추가
- [x]  spring project에서 sql 파일 수정
