### ISSUE TITLE
feat: 비회원 로그인 기능 개발

### ISSUE THREAD

**Issue by gmelon** [strangebros/nork-backend#19]
### 작업 개요
- 비회원 로그인 기능 개발

### 작업 내용
- 비회원 상태에서도 검색 등 기능을 사용할 수 있도록 비회원 로그인 API 및 관련 로직 개발

### Todo list
- [x] DB에 GUEST (READONLY) 계정 추가
- [x] Member에 Role 필드 추가
- [x] JWTProvider에서 token에 member role 추가
- [x] LoginInterceptor에서 memberRole 파싱, request에 저장하도록 변경
- [x] RoleCheckInterceptor 구현
  - 모든 url에서 `member` 권한을 유지하되, 검색 API 등 비회원도 가능한 API만 exclude 처리
- [x] GUEST login API 작성
