### ISSUE TITLE
fix: database의 reservation table / visited_review table 수정

### ISSUE THREAD

**Issue by sootudio** [strangebros/nork-backend#21]
### 예외 개요
- API 생성 중 db 수정사항이 생겨 reservation, visited_review 테이블을 수정합니다.

### 예외 원인
reservation
- visit_date의 column명이 직관적이지 않음 (일정을 시작하는 날짜가 되어야 함.)
- visit_date의 속성을 not null로 정해야 함.

visited_review
- visit_date를 시작 날짜와 끝 날짜로 분리해야할 필요성을 느낌. (하루 이상 있을 수도 있으므로)
- 시작 날짜와 끝 날짜로 나누면, 시작 시간과 끝 시간도 각각 포함시켜서 새로운 컬럼으로 만들기.

### 작업 내용
- reservation 테이블의 visit_date column의 이름과 속성 수정
- visited_review 테이블의 visit_date 나누고, 시간을 포함시킨 새로운 컬럼으로 만들기
- 변경 내용 프로젝트의 sql 파일에 적용시키기

### Todo list
reservation
- [x] visit_date 컬럼명 visit_start_date로 변경
- [x] 해당 컬럼의 속성값 `not null`로 변경

visited_review
- [x] visit_date, start_time, end_time 컬럼 삭제
- [x] start_datetime, end_datetime 컬럼 생성, type은 datetime, `not null` 속성

resources/sql/nork.sql
- [x] 변경사항 프로젝트의 sql 파일에 적용
