### ISSUE TITLE
feat: '현재 작업 중인 사람' 기능 개발

### ISSUE THREAD

**Issue by gmelon** [strangebros/nork-backend#26]
### 작업 개요
- '현재 작업 중인 사람' 기능 개발

### 작업 내용
- 작업이 시작되면 회원 정보를 redis에 기록
    - redis 구조는 "currentWorkers" 키의 map 내부에 "workspaceId" 를 키로 갖는 회원 정보 배열
- 실시간 작업 상태를 파악하기 위해 회원 정보에 expire을 두고, 주기적으로 refresh되지 않으면 자동으로 삭제되도록 구현
    - 우선 10분마다 요청 보내는 것으로 설정

### redis 저장 형식
```json
{
  "currentWorkers": {
    "3": [
      {
        "memberId": 1,
        "job": "개발자",
        "start_time": "2024-05-18T10:20:31"
      },
      {
        "memberId": 2,
        "job": "디자이너",
        "start_time": "2024-05-18T10:20:31"
      }
    ]
  }
}
```

### Todo list
- [x] redis server 구축
- [x] redis client 구현
    - [x] expire 설정 가능하도록 구현
- [x] currentWorkers 도메인 구현
- [x] (생성) workspaceId와 회원 정보를 받아 최초 생성 로직 구현
- [x] (갱신) workspaceId와 memberId를 받아 (계속해서 작업 중임을 알리기 위한) 갱신 로직 구현
- [x] (삭제) workspaceId와 memberId를 받아 (작업 완료 시 redis에서 삭제되도록 하기 위한) 삭제 로직 구현
