### ISSUE TITLE
feat: workspace 단건 조회 API 개발

### ISSUE THREAD

**Issue by gmelon** [strangebros/nork-backend#27]
### 작업 개요
- workspace 단건 조회 API 개발

### 작업 내용
- 기존 리스트 조회 필드에 '현재 작업 중 회원 정보', '장소 이미지'를 포함하는 단건 조회 API 개발
- workspace 리스트 조회 API Spec에서 '현재 작업 중 회원 정보', '장소 이미지' 제거

### Todo list
- [x] Tmap 단건 (poi) 조회 client 구현
- [x] Kakao image 검색 client 구현
- [x] API Spec 명세
- [x] workspace 단건 조회 서비스 구현
- [x] workspace 단건 조회 API 구현
- [x] workspace 리스트 조회 API Spec에서 '현재 작업 중 회원 정보', '장소 이미지' 제거
