### ISSUE TITLE
feat: 예약 삭제 API 작성

### ISSUE THREAD

**Issue by sootudio** [strangebros/nork-backend#33]
### 작업 개요
- 예약을 삭제하는 API 생성

### 작업 내용
- 예약에 대한 id를 보내면 삭제를 하는 API 생성

### Todo list
- [x] id 하나만 받으면 되기 때문에 따로 dto 생성 x
- [x] controller와 service에 삭제 메소드 생성
- [x] mapper에 메소드와 쿼리 생성
