### ISSUE TITLE
feat: 작업 시작, 종료 API

### ISSUE THREAD

**Issue by gmelon** [strangebros/nork-backend#38]
### 작업 개요
- 작업 시작, 종료 API 구현

### 작업 내용
- 작업 시작 시
    - redis에 currentWorker 정보 추가
- 작업 종료 시
    - redis에서 currentWorker 정보 삭제
    - reservation row 삭제
    - review row 추가

### Todo list
- [x] API Spec 명세
- [x] 작업 시작 service method 구현
- [x] 작업 종료 service method 구현
- [x] controller 구현
