### ISSUE TITLE
feat: 특정 직군에게 인기있는 워크스페이스 추천 API

### ISSUE THREAD

**Issue by sootudio** [strangebros/nork-backend#63]
### 작업 개요
- 메인 화면에서 특정 직군에게 인기있는 워크스페이스를 추천해주는 API 생성

### 작업 내용
- 특정 직군을 요청 dto 에 넣어서 특정 직군의 리뷰들만을 모아 rating 순으로 정렬하여 상위 10개의 워크스페이스 정보를 반환
- join해야 하는 테이블
    - member
    - visited_review
    - workspace
    - visited_workspace
    - workspace_keyword
    - keyword
~~우리 전체 테이블이 9갠데 그 중 6개를 join해서 만드는 게 맞는지 잘 모르겠습니다..~~
- 해당하는 워크스페이스 10개의 리스트 반환

### Todo list
- [ ] 요청 시에는 queryParatmeter로 position만 보내기. 따로 dto 필요 없음.
- [ ] 응답 dto 작성(reponse는 workspace 리스트 조회 참고하여 만들자.)
- [ ] 워크스페이스 서비스에서 검색
- [ ] mapping 메소드, 쿼리 작성
