### ISSUE TITLE
feat: (지도) 장소 검색 API 구현

### ISSUE THREAD

**Issue by gmelon** [strangebros/nork-backend#9]
### 작업 개요
- 장소 검색 API 구현

## 작업 내용
- 지도 페이지에서 사용할 장소 검색 API를 구현한다
1. 클라이언트에서 키워드와 카테고리(선택) 등 정보를 전달
2. 서버에서 tmap api 요청을 통해 장소를 검색
3. 불러온 장소와 매핑되는 자체 정보가 존재한다면 함께 묶어서 반환
    * (나의) 해당 장소 최근 방문 일자
    * 장소에서 현재 일하는 사람 숫자와 직업
    * 장소 평점
    * 장소 리뷰 이미지
 
### request
```json
{
    "query":"성산일출봉",
    "latitude":36.06,
    "longitude":127.02,
    "radius":3,
    "category":"A0101",
    "keywords": ["조용", "넓은"],

    // 페이지네이션
    "page": 1,
    "count": 10
}
```

### response
```json
{
    "status": 200,
    "message": "요청이 성공했습니다.",
    "data": {
        "poiId" : "123", // TMAP 장소 ID
        "name" : "장소 이름",
        "latitude": 36.06,
        "longitude": 127.02,
        "roadAddress": "도로명 주소",
        "category": "카페",

        "isWorkspaceInDatabase": true,
        // 아래부터는 isWorkspaceInDatabase가 true인 경우에만 non-null
        "id": 10412, // nork 장소 ID
        "imageUrl": "http://...",
        "rating": "4.5",
        "currentWorkers": {
            "개발자":2,
            "디자이너":1,
            "기획자":1
        }
        "recentVisitedDate": "2023-10-01T10:30:20", // 나의 최근 방문 일자 (존재한다면)
        "keywords": ["넓은", "쾌적한"]
    }
}
```

### Todo list
- [x] TMap API 호출 Client 구현
- [x] nork DB에서 poi_id에 해당하는 값들 조회 로직 구현
- [ ] TMap API 응답과 nork DB 정보와 병합하는 서비스 구현
